### ISSUE TITLE
Why screenshot making process takes 5 seconds?

### ISSUE THREAD

**Issue by OlegGulevskyy** [nashaofu/screenshots-rs#1]
Hello, your library is a big help as I did not find anything easier to work with but I wonder what makes the process of taking a screenshot take a whole of 5 seconds? For me on MacOS m1 it takes 5 seconds.
Can this be improved?
Thanks

**Comment by nashaofu** [comment]
Are you running in release mode？

**Comment by OlegGulevskyy** [comment]
Nope, this was in dev mode. Is release mode any different? Currently trying it

**Comment by OlegGulevskyy** [comment]
My bad, it's actually very fast with release mode :)
Thanks for pointing this out!
