### ISSUE TITLE
Memory leak when running screen.capture() multiple times [Linux]

### ISSUE THREAD

**Issue by mdacach** [nashaofu/screenshots-rs#11]
Hello, hope this message finds you well!

[Manjaro 21.3.2]

#### The Issue
When calling screen.capture() multiple times, the program increasingly consumes memory.

#### Example

Running screen.capture() in an infinite loop eventually leads to an OS freeze.
![image](https://user-images.githubusercontent.com/43617028/179855396-57c17eb2-8dd3-4db5-ab0b-0f2b946b34d8.png)

**Comment by mdacach** [comment]
[Related pull request with fix](https://github.com/nashaofu/screenshots-rs/pull/12)

**Comment by Stay1444** [comment]
This does not appear to be fixed. 
I'm on KDE Plasma using Wayland and the memory usage just increases until the process gets killed
