### ISSUE TITLE
no method named `capture` found for struct `Vec<Screen>` in the current scope

### ISSUE THREAD

**Issue by LeeeSe** [nashaofu/screenshots-rs#23]
error[E0599]: no method named `capture` found for struct `Vec<Screen>` in the current scope
  --> src/main.rs:10:28
   |
10 |     let mut image = screen.capture().unwrap();
   |                            ^^^^^^^ method not found in `Vec<Screen>`

error[E0609]: no field `id` on type `Vec<Screen>`
  --> src/main.rs:12:47
   |
12 |     fs::write(format!("target/{}.png", screen.id.to_string()), &buffer).unwrap();
   |                                               ^^ unknown field

error[E0599]: no method named `capture_area` found for struct `Vec<Screen>` in the current scope
  --> src/main.rs:14:20
   |
14 |     image = screen.capture_area(300, 300, 300, 300).unwrap();
   |                    ^^^^^^^^^^^^ method not found in `Vec<Screen>`

error[E0609]: no field `id` on type `Vec<Screen>`
  --> src/main.rs:16:49
   |
16 |     fs::write(format!("target/{}-2.png", screen.id.to_string()), &buffer).unwrap();
   |                                                 ^^ unknown field

Some errors have detailed explanations: E0599, E0609.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `screen_shot` due to 4 previous errors

**Comment by LeeeSe** [comment]
Chip：M1
System：macOS Ventura 13.0(Beta)

**Comment by nashaofu** [comment]
I don't have the MAC of the M1 chip，and the beta version of the system may not be supported

**Comment by zkxjzmswkwl** [comment]
Problem on Windows too.

**Comment by jlucaso1** [comment]
An example of working code:
```rust
let screens = Screen::all();
let screen = screens.unwrap()[0];
let image = screen.capture().unwrap();
```

**Comment by jowilkes** [comment]
readme sample code still has the issue; source example is fixed.
