### ISSUE TITLE
macOS screen capture error

### ISSUE THREAD

**Issue by TrueCarry** [nashaofu/screenshots-rs#38]
`let image = screen.capture().unwrap()` results in error

`Error wrong data size, expected 30882816 got 30883840`

I've checked and it seems that cg_data.bytes() returns more pixels than (w * h * 4), i've tried slicing it `cg_data.bytes().split_at(cg_image.width() * cg_image.height() * 4);` and it works.

**Comment by arividar** [comment]
I have the same problem - can you where where to fix this?

**Comment by arividar** [comment]
I have the same problem - can you where where to fix this?

**Comment by nashaofu** [comment]
I can't reproduce this problem. I modified the code. Can you help test it?

**Comment by arividar** [comment]
I had this problem with wrong data size an can confirm that it is fixed. Also #29 is fixed.
Yes, I am on Mac M1 ARM. Great job.

**Comment by nashaofu** [comment]
reference https://github.com/nashaofu/screenshots-rs/issues/29#issuecomment-1426574004

**Comment by nashaofu** [comment]
fixed #41
