### ISSUE TITLE
输出的buffer可以不强转成png不就rgb数值就行

### ISSUE THREAD

**Issue by pysrc** [nashaofu/screenshots-rs#42]
现在没有其他方法获取到rgb数组，但是需要的话再从png转过去也麻烦，能否提供rgb这种Vec\<u8\>

**Comment by nashaofu** [comment]
可以考虑提供

**Comment by poly000** [comment]
我的fork刚好做了这个）

**Comment by nikohpng** [comment]
有谁能提交到main分支吗？或者能提供下？我看到 request 里面有实现，是什么原因导致没有合并进行，如果需要完成相应的工作的话，可以给我解释下吗？也许我可以出点力

**Comment by poly000** [comment]
> 有谁能提交到main分支吗？或者能提供下？我看到 request 里面有实现，是什么原因导致没有合并进行，如果需要完成相应的工作的话，可以给我解释下吗？也许我可以出点力

之前实现被改回来了…… 切到了mainline的screenshot-rs
也许你可以去screenshot-rs上游改进api设计

**Comment by nashaofu** [comment]
#50 这个应该可以满足你们的功能
