### ISSUE TITLE
Transparent png's

### ISSUE THREAD

**Issue by biot-2131** [nashaofu/screenshots-rs#44]
Hi I'm using Ubuntu 22.04 and rustc 1.67.1, when I run the example code I get transparent png's. Am I missing something?

![445-2](https://user-images.githubusercontent.com/121760096/223704101-876c2e34-f95d-4fd6-95e2-f0277b122d47.png)
![472](https://user-images.githubusercontent.com/121760096/223704139-9f98a50a-4a2b-4e37-81e9-ad2fd25629d3.png)

**Comment by nashaofu** [comment]
Wayland Desktop?

**Comment by biot-2131** [comment]
No gnome, the standard ubuntu desktop running on a I7 with an Nvidia GTX 1050 Ti.

**Comment by biot-2131** [comment]
@nashaofu I created a new VM (one which i haven't been messing with) and screenshot's works fine. :-) Please close issue, Thanks
