### ISSUE TITLE
capture_area 时scale_factor影响了截图的尺寸

### ISSUE THREAD

**Issue by mtfcd** [nashaofu/screenshots-rs#46]
我在用capture_area截图时，截到的尺寸和我输入的参数一样，后来发现正好是乘了scale_factor的，不知道是不是有意设计成这样的？

**Comment by nashaofu** [comment]
是有意这样设计的，这样做的目的是为了获取高清的图片。你这边获取的图片只是变大了吧，不会出现截图的区域不正确吧

**Comment by mtfcd** [comment]
> 是有意这样设计的，这样做的目的是为了获取高清的图片。你这边获取的图片只是变大了吧，不会出现截图的区域不正确吧

一开始我是按物理坐标传参数，出现的结果和我预想的不一样，看了一下代码，发现是逻辑坐标，改成逻辑坐标就对了。功能没啥问题就是有点容易产生误解。
