### ISSUE TITLE
Screen::from_point()截图为什么没有符合预期的结果？

### ISSUE THREAD

**Issue by womeng2009** [nashaofu/screenshots-rs#5]
你好，请教一下：
1.使用from_point方法，生成的图片会比原始图片稍大一点
2.使用from_point方法并没有按指定位置生成，仍然是全屏幕，是我的使用方式错误吗？
![image](https://user-images.githubusercontent.com/64006143/175762307-115568be-9918-4f22-aa6a-0d6a7d1fd54e.png)

**Comment by nashaofu** [comment]
都是全屏截图，from_point是过去这个点所在的屏幕的截图

**Comment by nashaofu** [comment]
有新的API支持截取屏幕部分区域。https://github.com/nashaofu/screenshots-rs/tree/55cc50204252b9c9ebd758b85f4dc9df7682c4c7#screen-screen-capturer
