### ISSUE TITLE
Feature Request: Screenshot Region of Screen

### ISSUE THREAD

**Issue by mdacach** [nashaofu/screenshots-rs#6]
First of all, thank you very much for your work!
I would like to request a specific feature, which I've found missing both in this crate and in many similar ones:
* Screenshotting only a region of the screen

Similar to what [PyAutoGUI does with its `region` optional argument](https://pyautogui.readthedocs.io/en/latest/screenshot.html)

**Comment by nashaofu** [comment]
Whether this method can meet your needs?
`Screen::capture_area(&self, x: i32, y: i32, width: u32, height: u32) -> Option<Image>`

**Comment by mdacach** [comment]
Sorry for the delay! Yes, it is perfect!

**Comment by nashaofu** [comment]
supported: https://github.com/nashaofu/screenshots-rs#screen-screen-capturer. The coordinates are relative to the current screen.
