### ISSUE TITLE
Not working with the latest windows crate

### ISSUE THREAD

**Issue by hirokimoto** [nashaofu/screenshots-rs#74]
As you can see in the followin screenshot, if I bump up the version of windows crate, it failed to build.

<img width="681" alt="createdhdc" src="https://github.com/nashaofu/screenshots-rs/assets/22752054/7830749b-be61-4225-a986-c72c2b35aa58">

**Comment by nashaofu** [comment]
https://github.com/nashaofu/screenshots-rs/pull/73
